version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      # run tests!
      - run: npm test